export const routes = {
  root: '/',
  appRoot: '/app',
  settings: '/app/settings',
  auth: {
    login: '/login',
    signup: '/signup',
    forgotPassword: '/forgot-password',
    resetPassword: '/reset-password',
  },
  learner: {
    dashboard: '/app/dashboard',
    training: '/app/training',
    courses: '/app/courses',
    courseDetailPattern: '/app/courses/:courseId',
    courseDetail: (courseId: string) => `/app/courses/${courseId}`,
    assessment: '/app/assessment',
    coursePlayerPattern: '/app/learn/:courseId',
    coursePlayer: (courseId: string, from?: 'training') =>
      `/app/learn/${courseId}${from ? `?from=${from}` : ''}`,
    tips: '/app/tips',
    certificates: '/app/certificates',
  },
  community: {
    feed: '/app/community',
    postDetailPattern: '/app/community/:scope/posts/:postId',
    postDetail: (scope: string, postId: string) => `/app/community/${scope}/posts/${postId}`,
    postEditPattern: '/app/community/:scope/posts/:postId/edit',
    postEdit: (scope: string, postId: string) => `/app/community/${scope}/posts/${postId}/edit`,
    ideas: '/app/community/org/ideas',
    ideaNew: '/app/community/org/ideas/new',
    ideaEditPattern: '/app/community/org/ideas/edit/:ideaId',
    ideaEdit: (ideaId: string) => `/app/community/org/ideas/edit/${ideaId}`,
    ideaDetailPattern: '/app/community/org/ideas/:ideaId',
    ideaDetail: (ideaId: string) => `/app/community/org/ideas/${ideaId}`,
    events: '/app/events',
    resources: '/app/resources',
    resourcesLegacy: '/app/community/org/resources',
  },
  orgAdmin: {
    root: '/app/admin/org',
    settings: '/app/admin/org/settings',
    ideas: '/app/admin/org/ideas',
    moderation: '/app/admin/org/moderation',
  },
  platformAdmin: {
    organizations: '/app/admin/platform/organizations',
    organizationDetailPattern: '/app/admin/platform/organizations/:orgId',
    organizationDetail: (orgId: string) => `/app/admin/platform/organizations/${orgId}`,
    courses: '/app/admin/platform/courses',
    courseEditorPattern: '/app/admin/platform/courses/:courseId',
    courseEditor: (courseId: string) => `/app/admin/platform/courses/${courseId}`,
    analytics: '/app/admin/platform/analytics',
    settings: '/app/admin/platform/settings',
    moderation: '/app/admin/platform/moderation',
  },
} as const;
