import type { Config } from "tailwindcss";
import tailwindcssAnimate from "tailwindcss-animate";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    colors: {
      transparent: "transparent",
      current: "currentColor",
      inherit: "inherit",
      white: "#ffffff",
      black: "#000000",
      canvas: "var(--canvas)",
      surface: {
        DEFAULT: "var(--surface)",
        sunken: "var(--surface-sunken)",
        ink: "var(--surface-ink)",
      },
      ink: "var(--ink)",
      cream: "var(--cream)",
      interactive: {
        DEFAULT: "var(--interactive)",
        hover: "var(--interactive-hover)",
        tint: "var(--interactive-tint)",
        "tint-hover": "var(--interactive-tint-hover)",
      },
      focus: "var(--focus)",
      navy: {
        50: "var(--navy-50)",
        100: "var(--navy-100)",
        200: "var(--navy-200)",
        300: "var(--navy-300)",
        400: "var(--navy-400)",
        500: "var(--navy-500)",
        600: "var(--navy-600)",
        700: "var(--navy-700)",
        800: "var(--navy-800)",
        900: "var(--navy-900)",
      },
      neutral: {
        0: "var(--neutral-0)",
        50: "var(--neutral-50)",
        100: "var(--neutral-100)",
        150: "var(--neutral-150)",
        200: "var(--neutral-200)",
        300: "var(--neutral-300)",
        400: "var(--neutral-400)",
        500: "var(--neutral-500)",
        600: "var(--neutral-600)",
        700: "var(--neutral-700)",
        800: "var(--neutral-800)",
        900: "var(--neutral-900)",
      },
      green: {
        tint: "var(--green-tint)",
        pastel: "var(--green-pastel)",
        DEFAULT: "var(--green-base)",
        deep: "var(--green-deep)",
      },
      amber: {
        tint: "var(--amber-tint)",
        pastel: "var(--amber-pastel)",
        DEFAULT: "var(--amber-base)",
        deep: "var(--amber-deep)",
      },
      red: {
        tint: "var(--red-tint)",
        DEFAULT: "var(--red-base)",
        deep: "var(--red-deep)",
      },
      peri: {
        tint: "var(--peri-tint)",
        pastel: "var(--peri-pastel)",
        deep: "var(--peri-deep)",
      },
      "legacy-border": "hsl(var(--legacy-border))",
      "legacy-input": "hsl(var(--legacy-input))",
      "legacy-ring": "hsl(var(--legacy-ring))",
      "legacy-background": "hsl(var(--legacy-background))",
      "legacy-foreground": "hsl(var(--legacy-foreground))",
      "legacy-primary": {
        DEFAULT: "hsl(var(--legacy-primary))",
        foreground: "hsl(var(--legacy-primary-foreground))",
      },
      "legacy-secondary": {
        DEFAULT: "hsl(var(--legacy-secondary))",
        foreground: "hsl(var(--legacy-secondary-foreground))",
      },
      "legacy-destructive": {
        DEFAULT: "hsl(var(--legacy-destructive))",
        foreground: "hsl(var(--legacy-destructive-foreground))",
      },
      "legacy-muted": {
        DEFAULT: "hsl(var(--legacy-muted))",
        foreground: "hsl(var(--legacy-muted-foreground))",
      },
      "legacy-accent": {
        DEFAULT: "hsl(var(--legacy-accent))",
        foreground: "hsl(var(--legacy-accent-foreground))",
      },
      "legacy-success": {
        DEFAULT: "hsl(var(--legacy-success))",
        foreground: "hsl(var(--legacy-success-foreground))",
      },
      "legacy-warning": {
        DEFAULT: "hsl(var(--legacy-warning))",
        foreground: "hsl(var(--legacy-warning-foreground))",
      },
      "legacy-popover": {
        DEFAULT: "hsl(var(--legacy-popover))",
        foreground: "hsl(var(--legacy-popover-foreground))",
      },
      "legacy-card": {
        DEFAULT: "hsl(var(--legacy-card))",
        foreground: "hsl(var(--legacy-card-foreground))",
      },
      "legacy-dash": {
        ink: "#141a33",
        a1: "#a5b4fc",
        a2: "#f7d9a8",
        a3: "#a7e8c4",
      },
      "legacy-sidebar": {
        DEFAULT: "hsl(var(--legacy-sidebar-background))",
        foreground: "hsl(var(--legacy-sidebar-foreground))",
        primary: "hsl(var(--legacy-sidebar-primary))",
        "primary-foreground": "hsl(var(--legacy-sidebar-primary-foreground))",
        accent: "hsl(var(--legacy-sidebar-accent))",
        "accent-foreground": "hsl(var(--legacy-sidebar-accent-foreground))",
        border: "hsl(var(--legacy-sidebar-border))",
        ring: "hsl(var(--legacy-sidebar-ring))",
      },
    },
    borderRadius: {
      xs: "var(--radius-xs)",
      sm: "var(--radius-sm)",
      md: "var(--radius-md)",
      lg: "var(--radius-lg)",
      xl: "var(--radius-xl)",
      full: "var(--radius-full)",
      "legacy-base": "0.25rem",
      "legacy-sm": "calc(var(--legacy-radius) - 4px)",
      "legacy-md": "calc(var(--legacy-radius) - 2px)",
      "legacy-lg": "var(--legacy-radius)",
      "legacy-xl": "0.75rem",
      "legacy-2xl": "1rem",
      "legacy-3xl": "1.5rem",
    },
    boxShadow: {
      overlay: "var(--shadow-overlay)",
      float: "var(--shadow-float)",
      none: "none",
      "legacy-base": "0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)",
      "legacy-sm": "0 1px 2px 0 rgb(0 0 0 / 0.05)",
      "legacy-md": "0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)",
      "legacy-lg": "0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)",
    },
    extend: {
      fontFamily: {
        sans: ['Hanken Grotesk', 'system-ui', 'sans-serif'],
        display: ['Hanken Grotesk', 'system-ui', 'sans-serif'],
      },
      transitionDuration: {
        fast: "var(--motion-fast)",
        base: "var(--motion-base)",
        slow: "var(--motion-slow)",
      },
      transitionTimingFunction: {
        standard: "var(--ease-standard)",
        exit: "var(--ease-exit)",
        celebrate: "var(--ease-celebrate)",
      },
      fontSize: {
        display: ["1.75rem", { lineHeight: "1.15", letterSpacing: "-0.022em", fontWeight: "800" }],
        heading: ["1.375rem", { lineHeight: "1.25" }],
        subheading: ["1.0625rem", { lineHeight: "1.35" }],
        "body-reading": ["0.9375rem", { lineHeight: "1.7" }],
        "title-ui": ["1rem", { lineHeight: "1.3" }],
        "body-ui": ["0.875rem", { lineHeight: "1.5" }],
        label: "0.78125rem",
        caption: ["0.75rem", { lineHeight: "1.45" }],
        micro: "0.6875rem",
        code: "0.78125rem",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "pop-in": {
          "0%": { transform: "scale(0.3)" },
          "60%": { transform: "scale(1.18)" },
          "100%": { transform: "scale(1)" },
        },
        "bulb-wiggle": {
          "0%, 100%": { transform: "rotate(0) scale(1)" },
          "30%": { transform: "rotate(-12deg) scale(1.12)" },
          "65%": { transform: "rotate(9deg) scale(1.06)" },
        },
        shimmer: {
          "0%": { backgroundPosition: "100% 0" },
          "100%": { backgroundPosition: "0% 0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down var(--motion-base) var(--ease-standard)",
        "accordion-up": "accordion-up var(--motion-base) var(--ease-standard)",
        "pop-in": "pop-in 0.35s ease",
        "bulb-wiggle": "bulb-wiggle 0.55s ease",
        shimmer: "shimmer 1.5s linear infinite",
      },
    },
  },
  plugins: [tailwindcssAnimate],
} satisfies Config;
